workspace:
  base: /test
  path: platform-dev

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    environment:
      - DOCUMENT_ROOT=/test/platform-dev
    pull: true
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    pull: true
  selenium:
    image: wernight/phantomjs
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    pull: true
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"

clone:
  git:
    image: plugins/git:next
    depth: 1
    # The tags property is not documented but can be found in the following snippet of code
    # https://github.com/drone-plugins/drone-git/blob/master/plugin.go#L153
    tags: true

pipeline:
  site-build:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - composer install --ansi --no-suggest --no-progress
      - ./bin/phing build-platform-dev -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
      - ./bin/phing setup-drone-file-system -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
      - ./bin/phing install-platform  -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
    volumes:
      - /cache/${DRONE_REPO}-${DRONE_JOB_NUMBER}/composer:/root/.cache/composer

  phpcs:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./bin/phpcs
    when:
      matrix:
        CODE_COMPLIANCE: 1

  phpunit:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./bin/phpunit -c tests/phpunit.xml
    when:
      matrix:
        CODE_COMPLIANCE: 1

  behat:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./bin/behat -c build/tests/balancer/behat.${BEHAT_PROFILE=default}.${BEHAT_PART=0}.yml -p ${BEHAT_PROFILE=default} --colors -f pretty --strict
    when:
      matrix:
        CODE_COMPLIANCE: 0
        
  upload-screenshots:
    image: drillster/drone-rsync
    user: web_asda
    secrets: [ plugin_key, plugin_hosts ]
    source: tests/screenshots/
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME%%-reference}/screenshots/${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}/
    when:
      status: [ failure ]
      
matrix:
  include:
    - CODE_COMPLIANCE: 1
      # Communities, ec_resp (php 5.6)
    - BEHAT_PART: 0
      BEHAT_PROFILE: communities_ec_resp
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_communities
      THEME_DEFAULT: ec_resp
      # Communities, ec_resp (php 7.1)
      # SKIP php 7.1
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_resp

      # Communities, ec_europa (php 5.6)
    - BEHAT_PART: 0
      BEHAT_PROFILE: communities
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_communities
      THEME_DEFAULT: ec_europa
      # Communities, ec_europa (php 7.1)
      # SKIP php 7.1
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_europa

      # Standard, ec_europa (php 5.6)
    - BEHAT_PART: 0
      BEHAT_PROFILE: default
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_europa
    - BEHAT_PART: 1
      BEHAT_PROFILE: default
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_europa
    - BEHAT_PART: 2
      BEHAT_PROFILE: default
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_europa
    - BEHAT_PART: 3
      BEHAT_PROFILE: default
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_europa
      # Standard, ec_europa (php 7.1)
      # SKIP php 7.1
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 1
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 2
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 3
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa

      # Standard, ec_resp (php 5.6)
    - BEHAT_PART: 0
      BEHAT_PROFILE: standard_ec_resp
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp
    - BEHAT_PART: 1
      BEHAT_PROFILE: standard_ec_resp
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp
    - BEHAT_PART: 2
      BEHAT_PROFILE: standard_ec_resp
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp
    - BEHAT_PART: 3
      BEHAT_PROFILE: standard_ec_resp
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/httpd-php-dev:5.6
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp
      # Standard, ec_resp (php 7.1)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: standard_ec_resp
#      PLATFORM_PROFILE: multisite_drupal_standard
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      THEME_DEFAULT: ec_resp
#    - BEHAT_PART: 1
#      BEHAT_PROFILE: standard_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_resp
#    - BEHAT_PART: 2
#      BEHAT_PROFILE: standard_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_resp
#    - BEHAT_PART: 3
#      BEHAT_PROFILE: standard_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/httpd-php-dev:7.1-ubuntu
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_resp

  slack-notify-published:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: corebot
    icon_url: https://d30y9cdsu7xlg0.cloudfront.net/png/62766-200.png
    when:
      event: tag
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Platform ${DRONE_TAG} has been released and is available at https://asda.fpfis.tech.ec.europa.eu/ec-europa/platform-dev/dist/platform-${DRONE_TAG}.tar.gz
        Docker image fpfis/platform:${DRONE_TAG} is ready for use
        Minor subsites update to playground has started !
      {{else}}
        Platform ${DRONE_TAG} failed to be released
      {{/success}}

  slack-notify-released-rc:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: corebot
    icon_url: https://d30y9cdsu7xlg0.cloudfront.net/png/62766-200.png
    when:
      event: push
      branch: release-*
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Platform ${DRONE_BRANCH} release candidate is available at
        https://asda.fpfis.tech.ec.europa.eu/ec-europa/platform-dev/dist/platform-${DRONE_BRANCH}.tar.gz
        Docker image fpfis/platform:${DRONE_BRANCH} is ready for use
      {{else}}
        Platform ${DRONE_BRANCH} failed release candidate
      {{/success}}
