workspace:
  base: /test
  path: platform-dev

services:
  web:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    environment:
      - DOCUMENT_ROOT=/test/platform-dev
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: wernight/phantomjs
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"

clone:
  git:
    image: plugins/git:next
    depth: 1
    # The tags property is not documented but can be found in the following snippet of code
    # https://github.com/drone-plugins/drone-git/blob/master/plugin.go#L153
    tags: true

pipeline:
  composer-install:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    volumes:
      - /cache:/cache
    commands:
      - composer install

  build-platform:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    commands:
      - ./bin/phing build-platform-dev -D'composer.bin'='/usr/local/bin/composer' -D'behat.base_url'='http://web:8080/build' -D'behat.wd_host.url'='http://selenium:8910/wd/hub' -D'behat.browser.name'='phantomjs' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'

  install-platform:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    commands:
      - ./bin/phing install-platform -D'drupal.db.host'='mysql' -D'drupal.db.user'='root' -D'drupal.db.password'='' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'

  phpcs:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    commands:
      - ./bin/phpcs
    when:
      matrix:
        CODE_COMPLIANCE: 1

  phpunit:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    commands:
      - ./bin/phpunit -c tests/phpunit.xml
    when:
      matrix:
        CODE_COMPLIANCE: 1

  behat:
    image: ${IMAGE_PHP=fpfis/php56-dev}
    commands:
      - ./bin/behat -c build/tests/balancer/behat.${BEHAT_PROFILE=default}.${BEHAT_PART=0}.yml -p ${BEHAT_PROFILE=default} --colors -f pretty --strict --tags "${BEHAT_TAGS}"
    when:
      matrix:
        CODE_COMPLIANCE: 0
matrix:
  include:
#    - CODE_COMPLIANCE: 1
      # Communities, ec_resp (php 5.6)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php56-dev
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_resp
      # Communities, ec_resp (php 7.1)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_resp

      # Communities, ec_europa (php 5.6)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php56-dev
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_europa
      # Communities, ec_europa (php 7.1)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: communities
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_communities
#      THEME_DEFAULT: ec_europa

      # Standard, ec_europa (php 5.6)
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php56-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 1
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php56-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 2
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php56-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
      # Standard, ec_europa (php 7.1)
      # SKIP php 7.1
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 1
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa
#    - BEHAT_PART: 2
#      BEHAT_PROFILE: default
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_europa

      # Standard, ec_resp (php 5.6)
      # (1991 #12) Tracked changes, Then I should see the success message "NextEuropa Tracked Changes feature is now active on your site."
      # (1991 #12) Poetry, Notice: Undefined index: file in /test/platform-dev/profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php line 665
    - BEHAT_PART: 0
      BEHAT_PROFILE: standard_ec_resp
      BEHAT_TAGS: "@drone_tracked_changes,@drone_poetry_single"
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/php56-dev
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp

      # (1991 #13) The radio button with "Public local files served by the webserver." was not found on the page http://web:8080/build/file/add (Exception)
    - BEHAT_PART: 1
      BEHAT_PROFILE: standard_ec_resp
      BEHAT_TAGS: "@drone_multilingual"
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/php56-dev
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp

      # (1991 #14) Image upload: The string "has been created." was not found anywhere in the HTML response of the current page. (Behat\Mink\Exception\ExpectationException)
    - BEHAT_PART: 2
      BEHAT_PROFILE: standard_ec_resp
      BEHAT_TAGS: "@drone_images"
      CODE_COMPLIANCE: 0
      IMAGE_PHP: fpfis/php56-dev
      PLATFORM_PROFILE: multisite_drupal_standard
      THEME_DEFAULT: ec_resp
      # Standard, ec_resp (php 7.1)
      # SKIP php 7.1
#    - BEHAT_PART: 0
#      BEHAT_PROFILE: standard_ec_resp
#      PLATFORM_PROFILE: multisite_drupal_standard
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      THEME_DEFAULT: ec_resp
#    - BEHAT_PART: 1
#      BEHAT_PROFILE: standard_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_resp
#    - BEHAT_PART: 2
#      BEHAT_PROFILE: standard_ec_resp
#      CODE_COMPLIANCE: 0
#      IMAGE_PHP: fpfis/php71-dev
#      PLATFORM_PROFILE: multisite_drupal_standard
#      THEME_DEFAULT: ec_resp
